"use strict";
var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const request_1 = require("../../../../utility/request");
const mods_1 = __importDefault(require("../../../../tools/mods"));
const name = (user_id, type, object) => __awaiter(void 0, void 0, void 0, function* () {
    if (object.include_fails)
        // @ts-ignore
        object.include_fails = object.include_fails == true ? 1 : 0;
    const data = yield (0, request_1.request)(`https://osu.ppy.sh/api/v2/users/${user_id}/scores/${type}`, {
        method: 'GET',
        params: object,
    });
    // check if scores exists. Sometimes there can an error
    if (Array.isArray(data)) {
        const transform = data.map((v, i) => (Object.assign({ index: i + 1, mods_id: mods_1.default.id(v.mods.join('')) || 0 }, v)));
        if (object === null || object === void 0 ? void 0 : object.mods)
            return transform.filter(r => (r.mods_id & object.mods) > 0);
        return transform;
    }
    ;
    return data;
});
exports.default = name;
